INSERT INTO page_content (page, section, title, content, published) VALUES
-- ABOUT PAGE
('about', 'hero', 'About M.M College Wairaka', '{"subtitle": "Our Story", "description": "A government-aided boarding school in Wairaka, Jinja, shaping self-reliant leaders since 1953."}', true),
('about', 'history', 'Our History', '{"paragraphs": ["M.M College Wairaka was founded in 1953 by the Church of Uganda with a mission to provide quality education to the youth of Busoga and beyond.", "What started as a small secondary school has grown into one of the most respected educational institutions in the Eastern Region, with a reputation for academic excellence, discipline, and practical skills.", "The school motto Ad Maiora Natus Sum - Born for Greater Things - reflects our commitment to helping every student reach their full potential."], "timeline": [{"year": "1953", "event": "School founded by the Church of Uganda"}, {"year": "1970s", "event": "Expanded to A-Level offerings"}, {"year": "1990s", "event": "Alumni Trust Fund established"}, {"year": "2020s", "event": "Major infrastructure renovation programme"}]}', true),
('about', 'mission', 'Mission & Vision', '{"mission": "To provide holistic education that nurtures self-reliant, disciplined, and morally upright citizens who contribute positively to society.", "vision": "To be a leading centre of academic excellence and character formation in East Africa.", "values": ["Self-reliance - We do it ourselves", "Discipline - The foundation of success", "Integrity - Doing what is right", "Excellence - Striving for the best", "Service - Giving back to community"]}', true),
('about', 'leadership', 'School Leadership', '{"leaders": [{"name": "Mr. Samuel Balikowa", "role": "Head Teacher", "description": "Leading the school since 2018 with a focus on academic excellence and infrastructure development."}, {"name": "Mrs. Grace Kadondi", "role": "Deputy Head Teacher", "description": "Overseeing student welfare and academic programmes."}, {"name": "Mr. Moses Wamboga", "role": "Trust Fund Coordinator", "description": "Managing alumni contributions and school development projects."}]}', true),
('about', 'facilities', 'Our Facilities', '{"items": [{"name": "Science Laboratories", "description": "Fully equipped Physics, Chemistry, and Biology labs renovated in 2026."}, {"name": "Library", "description": "Over 5,000 volumes and digital resources for research and reading."}, {"name": "Sports Fields", "description": "Football pitch, netball court, and athletics track."}, {"name": "Workshop", "description": "Practical skills workshop for agriculture and technology."}, {"name": "Dormitories", "description": "Boarding facilities for over 800 students with modern amenities."}]}', true),

-- STUDENT LIFE PAGE
('student-life', 'hero', 'Student Life', '{"subtitle": "Life at Wairaka", "description": "Beyond academics, WACOS offers a vibrant residential community that shapes well-rounded individuals."}', true),
('student-life', 'overview', 'Overview', '{"paragraphs": ["Student life at M.M College Wairaka extends far beyond the classroom. Our residential community provides a structured environment where students develop independence, leadership, and lifelong friendships.", "From dawn prep to evening activities, every day is designed to build discipline and character. Students participate in sports, clubs, community service, and cultural activities that prepare them for life beyond school.", "With dedicated house parents, peer mentors, and a supportive community, every student finds their place at WACOS."]}', true),
('student-life', 'residential', 'Residential Life', '{"paragraphs": ["Our dormitories are more than just sleeping quarters - they are homes where students learn to live together, support each other, and develop lasting bonds.", "Each dormitory has a resident teacher and senior student leaders who provide guidance and mentorship.", "Students from different regions and backgrounds share experiences that broaden their perspectives and build cultural understanding."]}', true),
('student-life', 'activities', 'Activities & Programmes', '{"items": [{"name": "Morning Prep", "description": "Structured study time before classes to reinforce learning."}, {"name": "Sports & Games", "description": "Afternoon sports including football, netball, athletics, and volleyball."}, {"name": "Clubs & Societies", "description": "10 active clubs including Science, Agriculture, Debate, and Red Cross."}, {"name": "Community Service", "description": "Regular outreach programmes serving the Wairaka community."}, {"name": "Cultural Events", "description": "Music, dance, and drama celebrations throughout the year."}]}', true),

-- ATHLETICS PAGE
('athletics', 'hero', 'Athletics & Sports', '{"subtitle": "Champions in the Making", "description": "Sport builds discipline, teamwork, and resilience - qualities that define WACOS graduates."}', true),
('athletics', 'overview', 'Our Sports Program', '{"paragraphs": ["At M.M College Wairaka, sport is not just recreation - it is a training ground for life. Our athletics programme develops discipline, teamwork, and the competitive spirit that drives excellence in all areas.", "Students participate in inter-school competitions at district, regional, and national levels, bringing home trophies and medals that inspire the entire school community.", "Many of our alumni have gone on to represent Uganda in national and international competitions, carrying the WACOS spirit wherever they go."]}', true),
('athletics', 'sports', 'Our Sports', '{"items": [{"name": "Football", "description": "Busoga Schools Champions 2026. Training every afternoon under floodlights."}, {"name": "Netball", "description": "District champions with unbeaten record in the 2025/26 season."}, {"name": "Athletics", "description": "Track and field events including 100m, 400m, 800m, relays, and field events."}, {"name": "Volleyball", "description": "Growing programme with new courts and coaching staff."}, {"name": "Basketball", "description": "Inter-school competitions and friendly matches with regional schools."}]}', true),
('athletics', 'achievements', 'Recent Achievements', '{"achievements": [{"year": "2026", "achievement": "Busoga Schools Football Champions"}, {"year": "2026", "achievement": "District Netball Tournament Winners"}, {"year": "2025", "achievement": "Regional Athletics Bronze Medals"}, {"year": "2025", "achievement": "District Volleyball Runners-up"}]}', true),

-- GIVING PAGE
('giving', 'hero', 'Giving', '{"subtitle": "Support the Next Generation", "description": "Your generosity helps WACOS students access quality education and reach their full potential."}', true),
('giving', 'overview', 'Why Give', '{"paragraphs": ["M.M College Wairaka has produced leaders, professionals, and community builders for over seven decades. This legacy is sustained by alumni and friends who believe the next generation deserves the same chance they were given.", "Your contribution directly impacts students through scholarships, infrastructure, and programmes that make WACOS a place of opportunity for all."]}', true),
('giving', 'ways', 'Ways to Give', '{"ways": [{"name": "Scholarship Fund", "description": "Sponsor a bright student who cannot afford school fees. UGX 500,000 per term covers tuition, meals, and supplies.", "impact": "Over 100 students supported since 2020"}, {"name": "Trust Fund Contributions", "description": "Monthly contributions of UGX 10,000 or more fund infrastructure and development projects.", "impact": "UGX 45 million raised for renovations"}, {"name": "Alumni Class Giving", "description": "Organise your class to make a collective contribution. Every class reunion includes a giving component.", "impact": "32 classes active in giving"}, {"name": "In-Kind Donations", "description": "Donate books, equipment, furniture, or expertise. We welcome contributions of any kind.", "impact": "5,000+ books donated in 2025"}]}', true),
('giving', 'impact', 'Our Impact', '{"stats": [{"value": "100+", "label": "Students on scholarship"}, {"value": "UGX 45M", "label": "Raised for infrastructure"}, {"value": "32", "label": "Active class giving groups"}, {"value": "5,000+", "label": "Books donated"}]}', true),
('giving', 'faq', 'Frequently Asked Questions', '{"faqs": [{"question": "How do I make a donation?", "answer": "You can donate via Mobile Money to +256 332 277 476 (Reference: Your Name + Class Year), or bank transfer to the Wairaka Trust Fund account."}, {"question": "Is my donation tax-deductible?", "answer": "Yes, donations to registered educational institutions in Uganda are tax-deductible under the Income Tax Act."}, {"question": "Can I specify how my donation is used?", "answer": "Yes, you can direct your donation to scholarships, infrastructure, or a specific project. Contact the Trust Fund Coordinator for details."}, {"question": "How do I know my donation made a difference?", "answer": "We provide quarterly reports to all donors showing exactly how funds were used, with photos and student testimonials."}]}', true),

-- ACADEMICS PAGE
('academics', 'hero', 'Academics', '{"subtitle": "Excellence in Learning", "description": "Rigorous academics, practical skills, and dedicated teachers prepare students for university and beyond."}', true),
('academics', 'overview', 'Our Academic Program', '{"paragraphs": ["M.M College Wairaka offers a comprehensive academic programme that balances theoretical knowledge with practical skills. Our students consistently perform above national averages in UNEB examinations.", "With experienced teachers, modern laboratories, and a library stocked with resources, we provide an environment where students can excel in their chosen subjects.", "Beyond examinations, we emphasis critical thinking, problem-solving, and practical application of knowledge - skills that serve students well in higher education and careers."]}', true),
('academics', 'olevel', 'O-Level Programme', '{"subjects": ["Mathematics", "English Language", "Physics", "Chemistry", "Biology", "Geography", "History", "Commerce", "Agriculture", "Computer Studies"], "description": "Four-year programme preparing students for UCE examinations with a strong foundation in sciences and humanities."}', true),
('academics', 'alevel', 'A-Level Programme', '{"combinations": [{"name": "PCM", "subjects": ["Physics", "Chemistry", "Mathematics"], "careers": "Engineering, Medicine, Technology"}, {"name": "PCB", "subjects": ["Physics", "Chemistry", "Biology"], "careers": "Medicine, Pharmacy, Research"}, {"name": "MEG", "subjects": ["Mathematics", "Economics", "Geography"], "careers": "Business, Finance, Planning"}, {"name": "HEG", "subjects": ["History", "Economics", "Geography"], "careers": "Law, Public Administration, Education"}], "description": "Two-year advanced programme specialising in science, arts, or commercial combinations."}', true),
('academics', 'achievements', 'Academic Achievements', '{"achievements": [{"year": "2025", "achievement": "94% UNEB pass rate"}, {"year": "2025", "achievement": "3 students selected for national science competitions"}, {"year": "2024", "achievement": "Best performing school in Jinja District for Agriculture"}, {"year": "2024", "achievement": "Regional Debate Champions"}]}', true)
ON CONFLICT (page, section) DO NOTHING;
