import { createFileRoute } from "@tanstack/react-router";
import { IMAGES } from "@/lib/content";
import { ImageCarousel } from "@/components/image-carousel";

export const Route = createFileRoute("/about")({
  head: () => ({
    meta: [{ title: "About ,  M.M College Wairaka" },{ name: "description", content: "Founded in 1953, M.M College Wairaka is a government-aided boarding school built on discipline, hard work, and self-reliance. Olympic champion alumni. Bursaries for bright students." }],
    links: [{ rel: "canonical", href: "/about" }],
  }),
  component: AboutPage,
});

const Q=[{l:"Our Identity",h:"#identity"},{l:"Our Mission",h:"#mission"},{l:"Our History",h:"#history"},{l:"Our Values",h:"#values"},{l:"Facilities",h:"#facilities"}];
const M=[{y:"1953",t:"Founded",x:"The institution begins as a technical college, the brainchild of colonial governor Andrew Cohen, to provide skilled labour for the growing industries in Jinja."},{y:"1958",t:"Farm School Era",x:"Technical status transfers to Kyambogo. The institution becomes Muljibhai Madhvani Farm School."},{y:"1970",t:"Secondary School",x:"Parents demand conventional secondary education. The school becomes Muljibhai Madhvani College – Wairaka."},{y:"1973",t:"Wairaka College",x:"The Ugandan government abolishes foreign names. The school is renamed Wairaka College."},{y:"1982",t:"A-Level Introduced",x:"Wairaka College is upgraded to include A-Level, becoming a full secondary institution."},{y:"1986",t:"Madhvani Name Returns",x:"Following the return of Indians to Uganda, the Madhvani family reclaims the name."},{y:"2020",t:"Trust Fund Launched",x:"MMCWOSA establishes the Wairaka Trust Fund. Alumni contribute UGX 10,000 per month."},{y:"2024",t:"Revival Underway",x:"Alumni-led rehabilitation of laboratories. Asbestos removed from key buildings."}];
const V=[{n:"Integrity",d:"We act with honesty and transparency in all we do."},{n:"Discipline",d:"Self-control and commitment to excellence define our students."},{n:"Hard Work",d:"Nothing of value is achieved without sustained effort."},{n:"Teamwork",d:"We achieve more together than we ever could alone."},{n:"Efficiency",d:"We use our resources wisely and purposefully."},{n:"Industry",d:"We are productive, resourceful, and enterprising."},{n:"Commitment",d:"We see things through, especially when it gets difficult."},{n:"Determination",d:"We persist. We do it ourselves."}];
const F=[{n:"Physics Laboratory",d:"Renovated with alumni support. Equipped for UNEB practical examinations."},{n:"Chemistry Laboratory",d:"Fully renovated. One of the first projects completed by the Trust Fund."},{n:"Biology Laboratory",d:"Supporting science education with practical facilities."},{n:"Resource Centre",d:"Internet-connected hub for research and learning."},{n:"School Farm",d:"A nod to our origins as a farm school. Agriculture is part of our identity."},{n:"Boarding Facilities",d:"Accommodation for students from across Uganda’s 58 districts."}];

const ABOUT_IMAGES = [
  { src: IMAGES.campus, alt: "WACOS campus", caption: "The campus in Wairaka" },
  { src: IMAGES.academics, alt: "Students learning", caption: "Classroom learning" },
  { src: IMAGES.athletics, alt: "Sports at WACOS", caption: "Athletics and competition" },
  { src: IMAGES.studentLife, alt: "Student life", caption: "Life between classes" },
  { src: IMAGES.giving, alt: "Alumni", caption: "The alumni who keep Wairaka alive" },
];
function AboutPage() {
  return (<main>
    <section className="relative flex min-h-[60vh] items-end bg-foreground pb-16 pt-32">
      <img src={IMAGES.campus} alt="M.M College Wairaka campus" className="absolute inset-0 h-full w-full object-cover opacity-40" width={1600} height={900} />
      <div className="relative mx-auto max-w-6xl px-6">
        <p className="text-xs font-semibold uppercase tracking-[0.25em] text-white/60">About the College</p>
        <h1 className="mt-3 font-display text-5xl font-semibold leading-tight text-white md:text-6xl lg:text-7xl">Muljibhai Madhvani<br />College – Wairaka</h1>
        <p className="mt-4 max-w-xl text-lg text-white/70">A government-aided boarding school in Wairaka, Jinja ,  where discipline, hard work, and self-reliance have produced leaders, athletes, and citizens since 1953.</p>
      </div>
    </section>
    <section className="border-b border-border bg-cream"><div className="mx-auto flex max-w-6xl gap-6 overflow-x-auto px-6 py-4 text-sm font-medium text-muted-foreground">{Q.map((l)=>(<a key={l.h} href={l.h} className="shrink-0 transition-colors hover:text-primary">{l.l}</a>))}</div></section>
    <section id="identity" className="py-20"><div className="mx-auto grid max-w-6xl gap-12 px-6 lg:grid-cols-2"><div><p className="text-xs font-semibold uppercase tracking-[0.25em] text-primary">Our Identity</p><h2 className="mt-4 font-display text-4xl font-semibold leading-tight text-foreground md:text-5xl">Government-aided. Mixed. Boarding. Affordable.</h2><p className="mt-6 leading-relaxed text-muted-foreground">M.M College Wairaka is a government-aided, mixed, O-Level and A-Level boarding school located approximately 11 km from Jinja City, along the Jinja–Iganga Highway. Fees are UGX 709,800 per term ,  one of the most affordable boarding options in the region.</p><p className="mt-4 leading-relaxed text-muted-foreground">Students travel from 58 districts across Uganda to be here. They come for the discipline. They stay for the community. They leave with practical skills and a network that lasts a lifetime.</p></div><div className="space-y-6"><div className="rounded-2xl border border-border p-6"><p className="text-xs font-semibold uppercase tracking-wider text-primary">Motto</p><p className="mt-2 font-display text-2xl font-semibold text-foreground">“We Do It Ourselves”</p></div><div className="rounded-2xl border border-border p-6"><p className="text-xs font-semibold uppercase tracking-wider text-primary">Vision</p><p className="mt-2 leading-relaxed text-foreground">To expose students to quality all-round education and make our school a quality centre for excellence.</p></div><div className="rounded-2xl border border-border p-6"><p className="text-xs font-semibold uppercase tracking-wider text-primary">Location</p><p className="mt-2 text-foreground">Wairaka, Jinja, Uganda ,  along the Jinja–Iganga Highway</p></div></div></div></section>
    <section id="mission" className="bg-secondary py-20"><div className="mx-auto max-w-4xl px-6 text-center"><p className="text-xs font-semibold uppercase tracking-[0.25em] text-primary">Our Mission</p><h2 className="mt-4 font-display text-4xl font-semibold leading-tight text-foreground md:text-5xl">To produce self-reliant, patriotic, development-oriented, God-fearing and socially acceptable citizens ,  young people who do not wait for the world to change them, but change the world themselves.</h2><p className="mx-auto mt-6 max-w-2xl leading-relaxed text-muted-foreground">Every lesson, every club meeting, every community service drive is designed to prepare young people not just for exams, but for life. That is the WACOS difference.</p></div></section>
    <section id="history" className="py-20"><div className="mx-auto max-w-4xl px-6"><div className="text-center"><p className="text-xs font-semibold uppercase tracking-[0.25em] text-primary">Our History</p><h2 className="mt-4 font-display text-4xl font-semibold text-foreground md:text-5xl">From technical college to revival</h2><p className="mx-auto mt-4 max-w-xl text-muted-foreground">Born in 1953 to produce technical skills for Uganda’s industrial growth. It became a farm school, evolved into a secondary school, produced an Olympic champion, and is now being rebuilt by the alumni it created. This is not just a school. It is a living institution.</p></div><div className="mt-14">{M.map((m,i)=>(<div key={m.y} className="relative flex gap-8 pb-12 last:pb-0"><div className="relative flex flex-col items-center"><div className="h-4 w-4 rounded-full border-2 border-primary bg-cream" />{i<M.length-1&&<div className="mt-1 w-0.5 flex-1 bg-border" />}</div><div><div className="flex items-baseline gap-3"><p className="font-display text-2xl font-semibold text-primary">{m.y}</p><p className="text-sm font-semibold text-foreground">{m.t}</p></div><p className="mt-2 leading-relaxed text-muted-foreground">{m.x}</p></div></div>))}</div></div></section>
    <ImageCarousel images={ABOUT_IMAGES} title="Campus Gallery" />
    <section id="values" className="bg-foreground py-20"><div className="mx-auto max-w-6xl px-6"><div className="text-center"><p className="text-xs font-semibold uppercase tracking-[0.25em] text-primary">Core Values</p><h2 className="mt-4 font-display text-4xl font-semibold text-white md:text-5xl">What we stand for</h2></div><div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{V.map((v)=>(<div key={v.n} className="rounded-2xl border border-white/10 p-6"><h3 className="font-display text-xl font-semibold text-white">{v.n}</h3><p className="mt-2 text-sm leading-relaxed text-white/60">{v.d}</p></div>))}</div></div></section>
    <section id="facilities" className="py-20"><div className="mx-auto max-w-6xl px-6"><div className="text-center"><p className="text-xs font-semibold uppercase tracking-[0.25em] text-primary">Campus &amp; Facilities</p><h2 className="mt-4 font-display text-4xl font-semibold text-foreground md:text-5xl">Built by the community</h2><p className="mx-auto mt-4 max-w-xl text-muted-foreground">Your child will learn in laboratories rebuilt by the very alumni who sat in the same classrooms. The Physics and Chemistry labs are already renovated. More are coming. Every contribution rebuilds a facility your child will use.</p></div><div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{F.map((f)=>(<div key={f.n} className="rounded-2xl border border-border p-6 transition-shadow hover:shadow-md"><h3 className="font-display text-xl font-semibold text-foreground">{f.n}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{f.d}</p></div>))}</div></div></section>
    <section className="bg-primary py-16"><div className="mx-auto max-w-3xl px-6 text-center"><h2 className="font-display text-3xl font-semibold text-primary-foreground md:text-4xl">Be part of the revival</h2><p className="mx-auto mt-4 max-w-xl text-primary-foreground/80">Every contribution rebuilds a laboratory, a classroom, a future. Your child future is being built right now ,  by alumni who remember what WACOS gave them.</p><div className="mt-8 flex flex-wrap justify-center gap-4"><a href="/giving" className="rounded-full bg-white px-7 py-3 text-sm font-semibold text-foreground transition-all hover:bg-white/90">Support Wairaka</a><a href="/admissions" className="rounded-full border border-white/40 px-7 py-3 text-sm font-semibold text-white transition-all hover:bg-white/10">Apply Now</a></div></div></section>
  </main>);
}