import { createFileRoute } from "@tanstack/react-router";
import { IMAGES } from "@/lib/content";
import { usePageContent } from "@/hooks/usePageContent";

export const Route = createFileRoute("/academics")({
  head: () => ({
    meta: [{ title: "Academics ,  M.M College Wairaka" },{ name: "description", content: "94% university entry. Sciences, humanities, practical skills. UNEB examination centre in Jinja." }],
    links: [{ rel: "canonical", href: "/academics" }],
  }),
  component: AcademicsPage,
});

const OL=["English Language","Mathematics","Physics","Chemistry","Biology","Geography","History","Civic Education","Religious Education","Agriculture","Computer Studies","Commerce"];
const AS=["Mathematics","Physics","Chemistry","Biology","Computer Studies"];
const AR=["Literature in English","History","Economics","Divinity","Geography","Government"];
const DP=[{n:"Science & Laboratory",d:"Well-stocked physics, chemistry, and biology laboratories. Renovated through alumni support."},{n:"Humanities",d:"Literature, history, civic education, and religious studies."},{n:"Mathematics",d:"From O-Level foundational maths through A-Level pure and applied mathematics."},{n:"Agriculture & Practical Skills",d:"A school farm and practical sessions honouring our farm-school origins."},{n:"Technology",d:"Computer studies with internet-connected resource centre."},{n:"Sports & Co-Curricular",d:"Football, athletics, netball, volleyball, basketball, cricket, and clubs."}];
const SP=[{n:"O-Level (S1–S4)",d:"Four years covering both arts and science subjects. UNEB UCE examination centre.",i:["Arts + Science subjects","UNEB UCE examination centre","Comprehensive curriculum","Practical skills integration"]},{n:"A-Level (S5–S6)",d:"Two years of specialised study. Three essential + two subsidiary subjects.",i:["Arts or Sciences track","Three essential + two subsidiary subjects","Theory + practical lessons","Mock examinations + career guidance"]},{n:"Practical Skills Programme",d:"Every student participates in hands-on learning through agriculture, workshops, and community service.",i:["School farm operations","Laboratory practicals","Community outreach projects","Workshop sessions"]}];
function AcademicsPage() {
  const { content } = usePageContent("academics");
  const OL2 = content.olevel?.subjects?.length ? content.olevel.subjects : OL;
  const heroDesc = content.hero?.description || "94% of A-Level students go to university. But we do not just prepare students for exams ,  we prepare them for life. High challenge, high support, practical skills from day one.";
  const programsIntro = content.overview?.paragraphs?.length ? content.overview.paragraphs.join(" ") : "Every student at WACOS gets two things: a rigorous academic education and practical skills they can use immediately. This is not either/or. It is both.";
  const olevelDesc = content.olevel?.description || "Four years of broad-based education. Arts and sciences together. Your child discovers their strength before choosing a track. UNEB examination centre for UCE.";
  const alevelDesc = content.alevel?.description || "Two years of focused study. Three essential + two subsidiary subjects. Arts or Sciences track. 94% university entry rate. UNEB UACE examination centre.";
  const combos = content.alevel?.combinations;
  return (<main>
    <section className="relative flex min-h-[50vh] items-end bg-foreground pb-16 pt-32"><img src={IMAGES.academics} alt="Students at M.M College Wairaka" className="absolute inset-0 h-full w-full object-cover opacity-40" width={1600} height={900} /><div className="relative mx-auto max-w-6xl px-6"><p className="text-xs font-semibold uppercase tracking-[0.25em] text-white/60">Academic Programmes</p><h1 className="mt-3 font-display text-5xl font-semibold leading-tight text-white md:text-6xl lg:text-7xl">Academics</h1><p className="mt-4 max-w-2xl text-lg text-white/70">{heroDesc}</p></div></section>
    <section className="border-b border-border bg-cream"><div className="mx-auto flex max-w-6xl gap-6 overflow-x-auto px-6 py-4 text-sm font-medium text-muted-foreground">{[{l:"Programmes",h:"#programs"},{l:"O-Level",h:"#olevel"},{l:"A-Level",h:"#alevel"},{l:"Departments",h:"#departments"},{l:"Resources",h:"#resources"}].map((a)=><a key={a.h} href={a.h} className="shrink-0 transition-colors hover:text-primary">{a.l}</a>)}</div></section>
    <section id="programs" className="py-20"><div className="mx-auto max-w-6xl px-6"><div className="text-center"><p className="text-xs font-semibold uppercase tracking-[0.25em] text-primary">Our Programmes</p><h2 className="mt-4 font-display text-4xl font-semibold text-foreground md:text-5xl">High challenge, high support</h2><p className="mx-auto mt-4 max-w-2xl text-muted-foreground">{programsIntro}</p></div><div className="mt-14 grid gap-8 md:grid-cols-3">{SP.map((p)=><div key={p.n} className="rounded-2xl border border-border p-8"><h3 className="font-display text-2xl font-semibold text-foreground">{p.n}</h3><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{p.d}</p><ul className="mt-4 space-y-2">{p.i.map((x)=><li key={x} className="flex items-start gap-2 text-sm text-muted-foreground"><span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-primary" />{x}</li>)}</ul></div>)}</div></div></section>
    <section id="olevel" className="bg-secondary py-20"><div className="mx-auto max-w-6xl px-6"><div className="grid gap-12 lg:grid-cols-2"><div><p className="text-xs font-semibold uppercase tracking-[0.25em] text-primary">O-Level</p><h2 className="mt-4 font-display text-4xl font-semibold text-foreground md:text-5xl">Senior 1 – Senior 4</h2><p className="mt-4 leading-relaxed text-muted-foreground">{olevelDesc}</p><p className="mt-4 leading-relaxed text-muted-foreground">The curriculum balances academic subjects with agriculture, computer studies, and practical workshops ,  true to our farm-school origins and designed for the real world.</p></div><div><h3 className="font-display text-xl font-semibold text-foreground mb-4">Core Subjects</h3><div className="grid grid-cols-2 gap-3">{OL2.map((s: string)=><div key={s} className="rounded-xl bg-card border border-border px-4 py-3 text-sm font-medium text-foreground">{s}</div>)}</div></div></div></div></section>
    <section id="alevel" className="py-20"><div className="mx-auto max-w-6xl px-6"><div className="text-center"><p className="text-xs font-semibold uppercase tracking-[0.25em] text-primary">A-Level</p><h2 className="mt-4 font-display text-4xl font-semibold text-foreground md:text-5xl">Senior 5 – Senior 6</h2><p className="mx-auto mt-4 max-w-2xl text-muted-foreground">{alevelDesc}</p></div>{combos && combos.length ? (<div className="mt-12 grid gap-8 md:grid-cols-2">{combos.map((c: any) => (<div key={c.name} className="rounded-2xl border border-border p-8"><h3 className="font-display text-2xl font-semibold text-foreground">{c.name}</h3><p className="mt-2 text-sm text-muted-foreground">{c.careers}</p><div className="mt-4 flex flex-wrap gap-2">{c.subjects.map((s: string) => (<span key={s} className="rounded-full bg-primary/10 px-3 py-1 text-xs font-semibold text-primary">{s}</span>))}</div></div>))}</div>) : (<div className="mt-12 grid gap-8 md:grid-cols-2"><div className="rounded-2xl border border-border p-8"><h3 className="font-display text-2xl font-semibold text-foreground">Sciences</h3><div className="mt-4 space-y-2">{AS.map((s)=><div key={s} className="flex items-center gap-3 text-sm text-muted-foreground"><span className="h-1.5 w-1.5 rounded-full bg-primary" />{s}</div>)}</div></div><div className="rounded-2xl border border-border p-8"><h3 className="font-display text-2xl font-semibold text-foreground">Arts</h3><div className="mt-4 space-y-2">{AR.map((s)=><div key={s} className="flex items-center gap-3 text-sm text-muted-foreground"><span className="h-1.5 w-1.5 rounded-full bg-primary" />{s}</div>)}</div></div></div>)}<div className="mt-12 rounded-2xl bg-foreground p-8 text-center"><p className="text-sm font-semibold uppercase tracking-wider text-white/60">Examination Process</p><p className="mt-2 text-lg text-white">Admission → Subject Selection → Theory + Practical → Mocks → Career Guidance → UACE</p></div></div></section>
    <section id="departments" className="bg-foreground py-20"><div className="mx-auto max-w-6xl px-6"><div className="text-center"><p className="text-xs font-semibold uppercase tracking-[0.25em] text-primary">Academic Departments</p><h2 className="mt-4 font-display text-4xl font-semibold text-white md:text-5xl">Where potential becomes performance</h2></div><div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{DP.map((d)=><div key={d.n} className="rounded-2xl border border-white/10 p-6"><h3 className="font-display text-xl font-semibold text-white">{d.n}</h3><p className="mt-2 text-sm leading-relaxed text-white/60">{d.d}</p></div>)}</div></div></section>
    <section id="resources" className="py-20"><div className="mx-auto max-w-6xl px-6"><div className="text-center"><p className="text-xs font-semibold uppercase tracking-[0.25em] text-primary">Academic Resources</p><h2 className="mt-4 font-display text-4xl font-semibold text-foreground md:text-5xl">Every student gets the support they need to succeed</h2></div><div className="mt-12 grid gap-6 md:grid-cols-3"><div className="rounded-2xl border border-border p-8"><h3 className="font-display text-xl font-semibold text-foreground">Resource Centre</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">Internet-connected hub for research and learning. Your child has access to information from around the world.</p></div><div className="rounded-2xl border border-border p-8"><h3 className="font-display text-xl font-semibold text-foreground">Career Guidance</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">One-on-one career guidance helps students choose university courses, vocational paths, and career options. No student leaves WACOS without a plan.</p></div><div className="rounded-2xl border border-border p-8"><h3 className="font-display text-xl font-semibold text-foreground">UNEB Centre</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">Your child sits national examinations right here ,  no travel, no stress, familiar environment. UNEB centre for both O-Level and A-Level.</p></div></div></div></section>
    <section className="bg-primary py-16"><div className="mx-auto max-w-3xl px-6 text-center"><h2 className="font-display text-3xl font-semibold text-primary-foreground md:text-4xl">Ready to join?</h2><p className="mx-auto mt-4 max-w-xl text-primary-foreground/80">Your child deserves an education that prepares them for university and for life. Begin the conversation today.</p><div className="mt-8 flex flex-wrap justify-center gap-4"><a href="/admissions" className="rounded-full bg-white px-7 py-3 text-sm font-semibold text-foreground transition-all hover:bg-white/90">Apply Now</a><a href="/about" className="rounded-full border border-white/40 px-7 py-3 text-sm font-semibold text-white transition-all hover:bg-white/10">Learn About Us</a></div></div></section>
  </main>);
}