import { createFileRoute } from "@tanstack/react-router";
import { IMAGES } from "@/lib/content";

export const Route = createFileRoute("/athletics")({
  head: () => ({
    meta: [{ title: "Athletics — M.M College Wairaka" },{ name: "description", content: "WACOS athletics: eight sports, three seasons, and a tradition of scholar-athletes." }],
    links: [{ rel: "canonical", href: "/athletics" }],
  }),
  component: AthleticsPage,
});

const SPORTS=[{name:"Football",season:"Term 1 & 2",level:"First XI / Junior",highlight:"Busoga Schools Champions"},{name:"Athletics",season:"Term 2",level:"Track & Field",highlight:"Regional competitors"},{name:"Netball",season:"Term 1",level:"Senior / Junior",highlight:""},{name:"Volleyball",season:"Term 2",level:"Senior / Junior",highlight:""},{name:"Basketball",season:"Term 3",level:"Senior",highlight:""},{name:"Cricket",season:"Term 3",level:"Senior",highlight:""},{name:"Swimming",season:"Term 1",level:"Open",highlight:""},{name:"Rugby",season:"Term 2",level:"Senior",highlight:""}];
const CHEPTEGEI={name:"Joshua Cheptegei",text:"One of Uganda’s most successful international distance runners. Attended M.M College Wairaka for A-Level on a sports scholarship. The school recognised his athletic potential early. He went on to become a world champion and Olympic gold medallist. MMCWOSA later honoured him with the Pillar Honour — the highest distinction given to distinguished alumni."};
function AthleticsPage() {
  return (<main>
    <section className="relative flex min-h-[50vh] items-end bg-foreground pb-16 pt-32"><img src={IMAGES.athletics} alt="WACOS athletes" className="absolute inset-0 h-full w-full object-cover opacity-40" width={1600} height={900} /><div className="relative mx-auto max-w-6xl px-6"><p className="text-xs font-semibold uppercase tracking-[0.25em] text-white/60">Athletics</p><h1 className="mt-3 font-display text-5xl font-semibold leading-tight text-white md:text-6xl lg:text-7xl">Athletics</h1><p className="mt-4 max-w-2xl text-lg text-white/70">Eight sports across three terms. Scholar first, competitor always.</p></div></section>
    <section className="border-b border-border bg-cream"><div className="mx-auto flex max-w-6xl gap-6 overflow-x-auto px-6 py-4 text-sm font-medium text-muted-foreground">{[{l:"Sports",h:"#sports"},{l:"Cheptegei",h:"#cheptegei"}].map((a)=><a key={a.h} href={a.h} className="shrink-0 transition-colors hover:text-primary">{a.l}</a>)}</div></section>
    <section id="sports" className="py-20"><div className="mx-auto max-w-6xl px-6"><div className="text-center"><p className="text-xs font-semibold uppercase tracking-[0.25em] text-primary">Our Sports</p><h2 className="mt-4 font-display text-4xl font-semibold text-foreground md:text-5xl">When we take part, we win</h2></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{SPORTS.map((s)=><div key={s.name} className="group rounded-2xl border border-border p-6 transition-all hover:border-primary hover:shadow-md"><h3 className="font-display text-2xl font-semibold text-foreground">{s.name}</h3><p className="mt-2 text-sm text-muted-foreground">{s.season}</p><p className="text-xs text-muted-foreground">{s.level}</p>{s.highlight&&<p className="mt-3 inline-block rounded-full bg-primary/10 px-3 py-1 text-xs font-semibold text-primary">{s.highlight}</p>}</div>)}</div></div></section>
    <section id="cheptegei" className="bg-foreground py-20"><div className="mx-auto max-w-6xl px-6"><div className="text-center"><p className="text-xs font-semibold uppercase tracking-[0.25em] text-primary">Notable Athlete</p><h2 className="mt-4 font-display text-4xl font-semibold text-white md:text-5xl">{CHEPTEGEI.name}</h2></div><div className="mt-12 grid gap-8 lg:grid-cols-2"><div className="relative overflow-hidden rounded-2xl bg-white/5"><img src={IMAGES.athletics} alt="Joshua Cheptegei at M.M College Wairaka" className="h-full w-full object-cover" width={800} height={600} /><div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent" /><div className="absolute bottom-0 left-0 p-6"><p className="text-xs font-semibold uppercase tracking-wider text-white/60">A-Level Student</p><p className="mt-1 font-display text-lg font-semibold text-white">Sports Scholarship Recipient</p></div></div><div className="flex flex-col justify-center"><p className="leading-relaxed text-white/70">{CHEPTEGEI.text}</p><div className="mt-6 inline-block self-start rounded-full bg-primary/20 px-6 py-2 text-sm font-semibold text-primary">Pillar Honour Recipient</div><div className="mt-8 grid grid-cols-2 gap-4"><div className="rounded-xl bg-white/5 p-4 text-center"><p className="font-display text-2xl font-semibold text-primary">Olympic</p><p className="text-xs text-white/50">Gold Medallist</p></div><div className="rounded-xl bg-white/5 p-4 text-center"><p className="font-display text-2xl font-semibold text-primary">World</p><p className="text-xs text-white/50">Champion</p></div></div></div></div></div></section>
    <section className="bg-primary py-16"><div className="mx-auto max-w-3xl px-6 text-center"><h2 className="font-display text-3xl font-semibold text-primary-foreground md:text-4xl">Join the team</h2><p className="mx-auto mt-4 max-w-xl text-primary-foreground/80">Begin your application to M.M College Wairaka.</p><div className="mt-8 flex flex-wrap justify-center gap-4"><a href="/admissions" className="rounded-full bg-white px-7 py-3 text-sm font-semibold text-foreground transition-all hover:bg-white/90">Apply Now</a><a href="/student-life" className="rounded-full border border-white/40 px-7 py-3 text-sm font-semibold text-white transition-all hover:bg-white/10">Student Life</a></div></div></section>
  </main>);
}