import { createFileRoute } from "@tanstack/react-router";
import { IMAGES, TEAMS } from "@/lib/content";

export const Route = createFileRoute("/athletics")({
  head: () => ({
    meta: [{ title: "Athletics — M.M College Wairaka" },{ name: "description", content: "WACOS athletics: eight sports, three seasons, and a tradition of scholar-athletes." }],
    links: [{ rel: "canonical", href: "/athletics" }],
  }),
  component: AthleticsPage,
});

const HIGHLIGHTS=[{t:"Busoga Champions",d:"The first eleven lifted the Busoga Schools Football Championship, recovering from a one-goal half-time deficit to beat Jinja College 3–1."},{t:"National Science Fair",d:"The Science Club earned second place among ninety schools with a solar-powered drip irrigation controller."},{t:"4,000 Seedlings",d:"Students planted 4,000 tree seedlings in a single Saturday as part of the community reforestation drive."}];
const ALUMNI=[{n:"Joshua Cheptegei",d:"One of Uganda’s most successful international distance runners. Attended M.M College Wairaka for A-Level on a sports scholarship. Later honoured with the Pillar Honour — the highest distinction given to distinguished alumni."},{n:"Faith Alupo",d:"Woman Member of Parliament for Pallisa District. Attended M.M College Wairaka for A-Level, obtaining her UACE in 2003."}];
function AthleticsPage() {
  return (<main>
    <section className="relative flex min-h-[50vh] items-end bg-foreground pb-16 pt-32"><img src={IMAGES.athletics} alt="WACOS athletes" className="absolute inset-0 h-full w-full object-cover opacity-40" width={1600} height={900} /><div className="relative mx-auto max-w-6xl px-6"><p className="text-xs font-semibold uppercase tracking-[0.25em] text-white/60">Athletics</p><h1 className="mt-3 font-display text-5xl font-semibold leading-tight text-white md:text-6xl lg:text-7xl">Athletics</h1><p className="mt-4 max-w-2xl text-lg text-white/70">Eight sports. Three terms. A tradition of scholar-athletes who compete hard and represent Wairaka with pride.</p></div></section>
    <section className="border-b border-border bg-cream"><div className="mx-auto flex max-w-6xl gap-6 overflow-x-auto px-6 py-4 text-sm font-medium text-muted-foreground">{[{l:"Sports",h:"#sports"},{l:"Highlights",h:"#highlights"},{l:"Notable Alumni",h:"#alumni"}].map((a)=><a key={a.h} href={a.h} className="shrink-0 transition-colors hover:text-primary">{a.l}</a>)}</div></section>
    <section id="sports" className="py-20"><div className="mx-auto max-w-6xl px-6"><div className="text-center"><p className="text-xs font-semibold uppercase tracking-[0.25em] text-primary">Our Sports</p><h2 className="mt-4 font-display text-4xl font-semibold text-foreground md:text-5xl">When we take part, we win</h2><p className="mx-auto mt-4 max-w-xl text-muted-foreground">Nearly every student participates in at least one sport. Practices are scheduled around academics — scholar first, always.</p></div><div className="mt-12 overflow-hidden rounded-2xl border border-border"><table className="w-full text-left text-sm"><thead className="bg-primary text-primary-foreground"><tr><th className="px-6 py-4 font-semibold">Sport</th><th className="px-6 py-4 font-semibold">Season</th><th className="px-6 py-4 font-semibold">Level</th></tr></thead><tbody className="divide-y divide-border bg-card">{TEAMS.map((t)=><tr key={t.sport} className="transition-colors hover:bg-secondary"><td className="px-6 py-4 font-display text-lg font-semibold text-foreground">{t.sport}</td><td className="px-6 py-4 text-muted-foreground">{t.season}</td><td className="px-6 py-4 text-muted-foreground">{t.level}</td></tr>)}</tbody></table></div></div></section>
    <section id="highlights" className="bg-secondary py-20"><div className="mx-auto max-w-6xl px-6"><div className="text-center"><p className="text-xs font-semibold uppercase tracking-[0.25em] text-primary">Recent Highlights</p><h2 className="mt-4 font-display text-4xl font-semibold text-foreground md:text-5xl">Making headlines</h2></div><div className="mt-12 grid gap-6 md:grid-cols-3">{HIGHLIGHTS.map((h)=><div key={h.t} className="rounded-2xl bg-card border border-border p-6"><h3 className="font-display text-xl font-semibold text-foreground">{h.t}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{h.d}</p></div>)}</div></div></section>
    <section id="alumni" className="py-20"><div className="mx-auto max-w-6xl px-6"><div className="text-center"><p className="text-xs font-semibold uppercase tracking-[0.25em] text-primary">Notable Alumni</p><h2 className="mt-4 font-display text-4xl font-semibold text-foreground md:text-5xl">From Wairaka to the world</h2><p className="mx-auto mt-4 max-w-xl text-muted-foreground">Our alumni include international athletes, parliamentarians, and professionals who trace their foundations to Wairaka.</p></div><div className="mt-12 grid gap-8 md:grid-cols-2">{ALUMNI.map((a)=><div key={a.n} className="rounded-2xl border border-border p-8"><h3 className="font-display text-2xl font-semibold text-foreground">{a.n}</h3><p className="mt-3 leading-relaxed text-muted-foreground">{a.d}</p></div>)}</div></div></section>
    <section className="bg-primary py-16"><div className="mx-auto max-w-3xl px-6 text-center"><h2 className="font-display text-3xl font-semibold text-primary-foreground md:text-4xl">Join the team</h2><p className="mx-auto mt-4 max-w-xl text-primary-foreground/80">Begin your application to M.M College Wairaka.</p><div className="mt-8 flex flex-wrap justify-center gap-4"><a href="/admissions" className="rounded-full bg-white px-7 py-3 text-sm font-semibold text-foreground transition-all hover:bg-white/90">Apply Now</a><a href="/student-life" className="rounded-full border border-white/40 px-7 py-3 text-sm font-semibold text-white transition-all hover:bg-white/10">Student Life</a></div></div></section>
  </main>);
}