import { createFileRoute } from "@tanstack/react-router";
import { IMAGES, SCHOOL_NAME, SCHOOL_MOTTO } from "@/lib/content";
import { ImageCarousel } from "@/components/image-carousel";
import { usePageContent } from "@/hooks/usePageContent";

export const Route = createFileRoute("/student-life")({
  head: () => ({
    meta: [{ title: "Student Life ,  M.M College Wairaka" },{ name: "description", content: "10 clubs, 8 sports, community service, and boarding life at M.M College Wairaka. Where character is built outside the classroom." }],
    links: [{ rel: "canonical", href: "/student-life" }],
  }),
  component: StudentLifePage,
});


const SL_IMAGES = [
  { src: IMAGES.studentLife, alt: "Student life", caption: "Boarding life at WACOS" },
  { src: IMAGES.campus, alt: "Campus", caption: "The campus in Wairaka" },
  { src: IMAGES.athletics, alt: "Sports", caption: "Busoga Champions" },
  { src: IMAGES.academics, alt: "Academics", caption: "Learning in action" },
  { src: IMAGES.giving, alt: "Community", caption: "Community service" },
];
const QUICK_NAV = [
  { title: "Residential Life", icon: "home", href: "#residential" },
  { title: "Clubs & Societies", icon: "users", href: "#clubs" },
  { title: "Sports", icon: "trophy", href: "#sports" },
  { title: "Community Service", icon: "heart", href: "#service" },
  { title: "Arts & Culture", icon: "palette", href: "#arts" },
  { title: "Wellness", icon: "sparkles", href: "#wellness" },
];
function HeroSection({ desc }: { desc?: string }) {  return (    <section className="relative h-[60vh] min-h-[420px] flex items-end overflow-hidden">      <div className="absolute inset-0">        <img src={IMAGES.studentLife} alt="Students at M.M College Wairaka" className="h-full w-full object-cover object-center" />        <div className="absolute inset-0 bg-gradient-to-t from-black/70 via-black/20 to-transparent" />      </div>      <div className="relative z-10 w-full max-w-6xl mx-auto px-6 pb-16">        <h1 className="font-display text-5xl md:text-6xl lg:text-7xl text-white font-bold tracking-tight mb-4">Student Life</h1>        <p className="text-lg md:text-xl text-white/80 max-w-2xl font-body">{desc || "Where character is built, friendships are formed, and young people discover who they are meant to become."}</p>      </div>    </section>  );}
function PhilosophySection({ ps }: { ps: string[] }) {  return (    <section className="py-16 bg-white">      <div className="max-w-4xl mx-auto px-6 text-center">        {ps.map((p, i) => (<p key={i} className="text-stone-600 text-lg leading-relaxed font-body mb-6">{p}</p>))}      </div>    </section>  );}
function QuickNavCards() {  return (    <section className="py-12 bg-stone-50 border-y border-stone-200">      <div className="max-w-6xl mx-auto px-6">        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4">          {QUICK_NAV.map((item) => (            <a key={item.href} href={item.href} className="group flex flex-col items-center gap-3 rounded-2xl bg-white p-5 border border-stone-200 hover:border-green-800 hover:shadow-md transition-all text-center">              <div className="w-10 h-10 rounded-full bg-green-100 flex items-center justify-center text-green-800 group-hover:bg-green-800 group-hover:text-white transition-colors">                <span className="text-sm font-bold">{item.title.charAt(0)}</span>              </div>              <p className="text-sm font-semibold text-stone-800 group-hover:text-green-800 transition-colors">{item.title}</p>            </a>          ))}        </div>      </div>    </section>  );}
function ResidentialLife({ ps }: { ps: string[] }) {  return (    <section id="residential" className="py-20 scroll-mt-16">      <div className="max-w-6xl mx-auto px-6">        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-start">          <div className="relative overflow-hidden rounded-2xl aspect-[4/5]">            <img src={IMAGES.studentLife} alt="Boarding life at WACOS" className="absolute inset-0 h-full w-full object-cover" loading="lazy" />            <div className="absolute inset-0 bg-gradient-to-t from-black/40 to-transparent" />            <div className="absolute bottom-0 left-0 p-6">              <p className="text-xs font-semibold uppercase tracking-wider text-white/70">Boarding</p>              <p className="mt-1 font-display text-lg font-semibold text-white">More than a dormitory ,  a second family</p>            </div>          </div>          <div>            <p className="text-sm font-semibold text-green-800 uppercase tracking-widest mb-3">Residential Life</p>
            <h2 className="font-display text-3xl md:text-4xl text-stone-900 font-bold mb-6">Living and Learning Together</h2>
            {ps.map((p, i) => (<p key={i} className="text-stone-600 text-lg leading-relaxed font-body mb-4">{p}</p>))}
          </div>        </div>      </div>    </section>  );}
const CLUBS = [  { name: "Science Club", desc: "Students design, build, and test prototypes. The club earned second place at the National Schools Science Fair with a solar-powered irrigation controller built entirely in the college workshop." },  { name: "Agriculture Club", desc: "Running the school nursery and farm, students grow seedlings from seed, manage crops, and learn practical agricultural skills that connect directly to the school’s founding identity as a farm school." },  { name: "Girl Guides", desc: "Building leadership, service, and resilience through structured programmes and community engagement." },  { name: "Debating Society", desc: "Students sharpen critical thinking and public speaking through inter-school competitions and weekly practice sessions." },];
function ClubsSection() {  return (    <section id="clubs" className="py-20 bg-stone-50 scroll-mt-16">      <div className="max-w-6xl mx-auto px-6">        <div className="text-center mb-12">          <p className="text-sm font-semibold text-green-800 uppercase tracking-widest mb-3">Clubs & Societies</p>          <h2 className="font-display text-3xl md:text-4xl text-stone-900 font-bold">Lead, Organise, Do</h2>          <p className="mt-4 text-stone-600 text-lg font-body max-w-3xl mx-auto">Ten student-run organisations. Zero passengers. Every member leads, organises, and learns by doing. These are not课外 activities ,  they are where the motto comes alive.</p>        </div>        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">          {CLUBS.map((club) => (            <div key={club.name} className="rounded-2xl bg-white p-8 border border-stone-200">              <h3 className="font-display text-xl font-bold text-stone-900 mb-3">{club.name}</h3>              <p className="text-stone-600 leading-relaxed font-body">{club.desc}</p>            </div>          ))}        </div>      </div>    </section>  );}
function SportsSection() {  return (    <section id="sports" className="py-20 scroll-mt-16">      <div className="max-w-6xl mx-auto px-6">        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-start">          <div>            <p className="text-sm font-semibold text-green-800 uppercase tracking-widest mb-3">Sports & Athletics</p>            <h2 className="font-display text-3xl md:text-4xl text-stone-900 font-bold mb-6">When we take part, we win</h2>            <p className="text-stone-600 text-lg leading-relaxed font-body mb-4">Eight sports across three terms. Football, athletics, netball, volleyball, basketball, cricket, swimming, and rugby. Students compete at school, district, and regional level.</p>            <p className="text-stone-600 text-lg leading-relaxed font-body mb-6">Sport at WACOS is not a distraction from academics ,  it is an extension of the school motto. Busoga Champions in football. Regional competitors in athletics. Your child will compete, win, and learn what teamwork really means.</p>            <div className="grid grid-cols-3 gap-4">              <div className="rounded-xl bg-stone-50 border border-stone-200 p-4 text-center">                <p className="font-display text-2xl font-bold text-green-800">8</p>                <p className="text-xs text-stone-500">Sports</p>              </div>              <div className="rounded-xl bg-stone-50 border border-stone-200 p-4 text-center">                <p className="font-display text-2xl font-bold text-green-800">3</p>                <p className="text-xs text-stone-500">Terms</p>              </div>              <div className="rounded-xl bg-stone-50 border border-stone-200 p-4 text-center">                <p className="font-display text-2xl font-bold text-green-800">1st</p>                <p className="text-xs text-stone-500">Busoga Champions</p>              </div>            </div>          </div>          <div className="relative overflow-hidden rounded-2xl aspect-[4/5]">            <img src={IMAGES.athletics} alt="WACOS sports" className="absolute inset-0 h-full w-full object-cover" loading="lazy" />            <div className="absolute inset-0 bg-gradient-to-t from-black/40 to-transparent" />            <div className="absolute bottom-0 left-0 p-6">              <p className="text-xs font-semibold uppercase tracking-wider text-white/70">Athletics</p>              <p className="mt-1 font-display text-lg font-semibold text-white">Busoga Schools Champions</p>            </div>          </div>        </div>      </div>    </section>  );}
function ServiceSection() {  return (    <section id="service" className="py-20 bg-stone-50 scroll-mt-16">      <div className="max-w-6xl mx-auto px-6">        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-start">          <div className="relative overflow-hidden rounded-2xl aspect-[4/5]">            <img src={IMAGES.giving} alt="Community service at WACOS" className="absolute inset-0 h-full w-full object-cover" loading="lazy" />            <div className="absolute inset-0 bg-gradient-to-t from-black/40 to-transparent" />            <div className="absolute bottom-0 left-0 p-6">              <p className="text-xs font-semibold uppercase tracking-wider text-white/70">Outreach</p>              <p className="mt-1 font-display text-lg font-semibold text-white">4,000 seedlings in a single Saturday</p>            </div>          </div>          <div>            <p className="text-sm font-semibold text-green-800 uppercase tracking-widest mb-3">Community Service</p>            <h2 className="font-display text-3xl md:text-4xl text-stone-900 font-bold mb-6">The Motto in Action</h2>            <p className="text-stone-600 text-lg leading-relaxed font-body mb-4">Students do not just study the motto ,  they live it. Last year, 400 students planted 4,000 tree seedlings in a single Saturday. The seedlings were raised entirely by students in the school nursery. Every seedling is theirs. The shade belongs to the community.</p>            <p className="text-stone-600 text-lg leading-relaxed font-body mb-4">The nursery is run entirely by students. Seedlings grow from seed collected during holidays. This is what "We Do It Ourselves" looks like in practice.</p>            <p className="text-stone-600 text-lg leading-relaxed font-body">Your child will not just read about community service ,  they will lead it.</p>          </div>        </div>      </div>    </section>  );}
function ArtsSection() {  return (    <section id="arts" className="py-20 scroll-mt-16">      <div className="max-w-6xl mx-auto px-6">        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-start">          <div>            <p className="text-sm font-semibold text-green-800 uppercase tracking-widest mb-3">Arts & Culture</p>            <h2 className="font-display text-3xl md:text-4xl text-stone-900 font-bold mb-6">Express and Create</h2>            <p className="text-stone-600 text-lg leading-relaxed font-body mb-4">From Busoga traditional dance to inter-school drama competitions, students find platforms to express who they are and where they come from. The arts programme builds confidence, creativity, and cultural pride.</p>            <p className="text-stone-600 text-lg leading-relaxed font-body">Your child will perform, create, and represent WACOS on stages across the region.</p>          </div>          <div className="relative overflow-hidden rounded-2xl aspect-[4/5]">            <img src={IMAGES.campus} alt="Arts and culture at WACOS" className="absolute inset-0 h-full w-full object-cover" loading="lazy" />            <div className="absolute inset-0 bg-gradient-to-t from-black/40 to-transparent" />            <div className="absolute bottom-0 left-0 p-6">              <p className="text-xs font-semibold uppercase tracking-wider text-white/70">Culture</p>              <p className="mt-1 font-display text-lg font-semibold text-white">Express, create, perform</p>            </div>          </div>        </div>      </div>    </section>  );}
function WellnessSection() {  return (    <section id="wellness" className="py-20 bg-stone-50 scroll-mt-16">      <div className="max-w-6xl mx-auto px-6">        <div className="text-center mb-12">          <p className="text-sm font-semibold text-green-800 uppercase tracking-widest mb-3">Wellness & Mentoring</p>          <h2 className="font-display text-3xl md:text-4xl text-stone-900 font-bold">Building the whole person ,  body, mind, and character</h2>        </div>        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">          <div className="rounded-2xl bg-white p-8 border border-stone-200">            <h3 className="font-display text-xl font-bold text-stone-900 mb-3">Career Guidance</h3>            <p className="text-stone-600 leading-relaxed font-body">Seminars and one-on-one sessions help students understand their options after O-Level and A-Level. From university pathways to vocational training, students leave with a plan.</p>          </div>          <div className="rounded-2xl bg-white p-8 border border-stone-200">            <h3 className="font-display text-xl font-bold text-stone-900 mb-3">Medical Bootcamps</h3>            <p className="text-stone-600 leading-relaxed font-body">Health education and medical outreach ensure students understand their bodies, their rights, and how to stay well ,  in school and beyond.</p>          </div>          <div className="rounded-2xl bg-white p-8 border border-stone-200">            <h3 className="font-display text-xl font-bold text-stone-900 mb-3">Peer Mentoring</h3>            <p className="text-stone-600 leading-relaxed font-body">Senior students guide juniors through the transition to secondary school. Every student is known, supported, and challenged to grow.</p>          </div>        </div>      </div>    </section>  );}
function CTASection() {  return (    <section className="bg-green-900 py-20">      <div className="max-w-4xl mx-auto px-6 text-center">        <h2 className="font-display text-3xl md:text-4xl text-white font-bold mb-4">Experience it for yourself</h2>        <p className="text-white/70 text-lg mb-8 max-w-2xl mx-auto font-body">Come see what a day in the life of a WACOS student looks like. Walk the campus. Meet the house parents. Talk to current students. We welcome prospective families to visit Wairaka.</p>        <div className="flex flex-wrap justify-center gap-4">          <a href="/admissions" className="inline-flex items-center gap-2 bg-white text-green-900 px-8 py-4 rounded-full font-semibold text-lg hover:bg-stone-100 transition-colors">Apply Now</a>          <a href="/contact" className="inline-flex items-center gap-2 border border-white/40 text-white px-8 py-4 rounded-full font-semibold text-lg hover:bg-white/10 transition-colors">Visit Us</a>        </div>      </div>    </section>  );}function ActivitiesStrip({ items }: { items: { name: string; description: string }[] }) {
  return (
    <section className="relative overflow-hidden py-12 bg-stone-50 border-y border-stone-200">
      {/* Pillar image faded corner-to-corner behind the section */}
      <img
        src="/hero-poster.png"
        alt=""
        aria-hidden="true"
        className="pointer-events-none absolute inset-0 h-full w-full object-cover object-center opacity-[0.12]"
      />
      <div className="relative max-w-6xl mx-auto px-6">        <div className="text-center mb-10">          <p className="text-sm font-semibold text-green-800 uppercase tracking-widest mb-3">Daily Life</p>          <h2 className="font-display text-3xl md:text-4xl text-stone-900 font-bold">A day at Wairaka</h2>        </div>        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">          {items.map((item) => (            <div key={item.name} className="rounded-2xl bg-white p-6 border border-stone-200">              <h3 className="font-display text-lg font-bold text-stone-900 mb-2">{item.name}</h3>              <p className="text-stone-600 text-sm leading-relaxed font-body">{item.description}</p>            </div>          ))}        </div>      </div>    </section>  );}
function StudentLifePage() {  const { content } = usePageContent("student-life");
  const heroDesc = content.hero?.description;
  const philoPs = content.overview?.paragraphs?.length ? content.overview.paragraphs : ["At {SCHOOL_NAME}, student life is grounded in our core values: Discipline, Hard work, and Self-reliance. Our motto ,  \"{SCHOOL_MOTTO}\" ,  is not decoration. It is an instruction. Through house-parent mentoring, 10 active clubs, 8 sports, community service, and practical skills programmes, students are encouraged to take responsibility, explore their potential, and build character that lasts well beyond graduation.", "Parents send us children. We send back leaders. That is the WACOS promise."];
  const resiPs = content.residential?.paragraphs?.length ? content.residential.paragraphs : ["Boarding students at {SCHOOL_NAME} live, study, and grow together in supervised dormitories. House parents who mentor and support students through their secondary school years create a second family environment ,  one built on structure, accountability, and genuine care.", "Throughout the year, conversations in the dorm ,  both formal and informal ,  provide moments for students to reflect on core values, health and wellness, and their relationships with peers. Faculty residents guide students through discussions and activities at moments in the year when the content is most relevant.", "More than anything, our residential community gives students the space to discover who they are and who they want to become. With adults who care about them nearby, students flourish."];
  const activities = content.activities?.items || [];
  return (    <div>      <HeroSection desc={heroDesc} />      <PhilosophySection ps={philoPs} />      <ImageCarousel images={SL_IMAGES} title="Campus Life" />
      <QuickNavCards />      <main>        <ResidentialLife ps={resiPs} />        {activities.length > 0 && <ActivitiesStrip items={activities} />}        <ClubsSection />        <SportsSection />        <ServiceSection />        <ArtsSection />        <WellnessSection />      </main>      <CTASection />    </div>  );}