/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcademicsRouteImport } from './routes/academics'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AlumniRouteImport } from './routes/alumni'
import { Route as AthleticsRouteImport } from './routes/athletics'
import { Route as ClubsRouteImport } from './routes/clubs'
import { Route as GivingRouteImport } from './routes/giving'
import { Route as StudentLifeRouteImport } from './routes/student-life'
import { Route as CampusStoresIndexRouteImport } from './routes/campus-stores.index'
import { Route as CampusStoresSlugRouteImport } from './routes/campus-stores.$slug'
import { Route as ClubsSlugRouteImport } from './routes/clubs.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsRoute = AcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumniRoute = AlumniRouteImport.update({
  id: '/alumni',
  path: '/alumni',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleticsRoute = AthleticsRouteImport.update({
  id: '/athletics',
  path: '/athletics',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsRoute = ClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const GivingRoute = GivingRouteImport.update({
  id: '/giving',
  path: '/giving',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLifeRoute = StudentLifeRouteImport.update({
  id: '/student-life',
  path: '/student-life',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusStoresIndexRoute = CampusStoresIndexRouteImport.update({
  id: '/campus-stores/',
  path: '/campus-stores/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusStoresSlugRoute = CampusStoresSlugRouteImport.update({
  id: '/campus-stores/$slug',
  path: '/campus-stores/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsSlugRoute = ClubsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ClubsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/alumni': typeof AlumniRoute
  '/athletics': typeof AthleticsRoute
  '/clubs': typeof ClubsRouteWithChildren
  '/giving': typeof GivingRoute
  '/student-life': typeof StudentLifeRoute
  '/campus-stores/$slug': typeof CampusStoresSlugRoute
  '/clubs/$slug': typeof ClubsSlugRoute
  '/campus-stores/': typeof CampusStoresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/alumni': typeof AlumniRoute
  '/athletics': typeof AthleticsRoute
  '/clubs': typeof ClubsRouteWithChildren
  '/giving': typeof GivingRoute
  '/student-life': typeof StudentLifeRoute
  '/campus-stores/$slug': typeof CampusStoresSlugRoute
  '/clubs/$slug': typeof ClubsSlugRoute
  '/campus-stores': typeof CampusStoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/alumni': typeof AlumniRoute
  '/athletics': typeof AthleticsRoute
  '/clubs': typeof ClubsRouteWithChildren
  '/giving': typeof GivingRoute
  '/student-life': typeof StudentLifeRoute
  '/campus-stores/$slug': typeof CampusStoresSlugRoute
  '/clubs/$slug': typeof ClubsSlugRoute
  '/campus-stores/': typeof CampusStoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academics'
    | '/admissions'
    | '/alumni'
    | '/athletics'
    | '/clubs'
    | '/giving'
    | '/student-life'
    | '/campus-stores/$slug'
    | '/clubs/$slug'
    | '/campus-stores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academics'
    | '/admissions'
    | '/alumni'
    | '/athletics'
    | '/clubs'
    | '/giving'
    | '/student-life'
    | '/campus-stores/$slug'
    | '/clubs/$slug'
    | '/campus-stores'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academics'
    | '/admissions'
    | '/alumni'
    | '/athletics'
    | '/clubs'
    | '/giving'
    | '/student-life'
    | '/campus-stores/$slug'
    | '/clubs/$slug'
    | '/campus-stores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademicsRoute: typeof AcademicsRoute
  AdmissionsRoute: typeof AdmissionsRoute
  AlumniRoute: typeof AlumniRoute
  AthleticsRoute: typeof AthleticsRoute
  ClubsRoute: typeof ClubsRouteWithChildren
  GivingRoute: typeof GivingRoute
  StudentLifeRoute: typeof StudentLifeRoute
  CampusStoresSlugRoute: typeof CampusStoresSlugRoute
  CampusStoresIndexRoute: typeof CampusStoresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics': {
      id: '/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AcademicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumni': {
      id: '/alumni'
      path: '/alumni'
      fullPath: '/alumni'
      preLoaderRoute: typeof AlumniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athletics': {
      id: '/athletics'
      path: '/athletics'
      fullPath: '/athletics'
      preLoaderRoute: typeof AthleticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs': {
      id: '/clubs'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof ClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giving': {
      id: '/giving'
      path: '/giving'
      fullPath: '/giving'
      preLoaderRoute: typeof GivingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-life': {
      id: '/student-life'
      path: '/student-life'
      fullPath: '/student-life'
      preLoaderRoute: typeof StudentLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus-stores/': {
      id: '/campus-stores/'
      path: '/campus-stores'
      fullPath: '/campus-stores/'
      preLoaderRoute: typeof CampusStoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus-stores/$slug': {
      id: '/campus-stores/$slug'
      path: '/campus-stores/$slug'
      fullPath: '/campus-stores/$slug'
      preLoaderRoute: typeof CampusStoresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/$slug': {
      id: '/clubs/$slug'
      path: '/$slug'
      fullPath: '/clubs/$slug'
      preLoaderRoute: typeof ClubsSlugRouteImport
      parentRoute: typeof ClubsRoute
    }
  }
}

interface ClubsRouteChildren {
  ClubsSlugRoute: typeof ClubsSlugRoute
}

const ClubsRouteChildren: ClubsRouteChildren = {
  ClubsSlugRoute: ClubsSlugRoute,
}

const ClubsRouteWithChildren = ClubsRoute._addFileChildren(ClubsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademicsRoute: AcademicsRoute,
  AdmissionsRoute: AdmissionsRoute,
  AlumniRoute: AlumniRoute,
  AthleticsRoute: AthleticsRoute,
  ClubsRoute: ClubsRouteWithChildren,
  GivingRoute: GivingRoute,
  StudentLifeRoute: StudentLifeRoute,
  CampusStoresSlugRoute: CampusStoresSlugRoute,
  CampusStoresIndexRoute: CampusStoresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
