/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcademicsRouteImport } from './routes/academics'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AlumniRouteImport } from './routes/alumni'
import { Route as AthleticsRouteImport } from './routes/athletics'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ClubsRouteImport } from './routes/clubs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GivingRouteImport } from './routes/giving'
import { Route as StudentLifeRouteImport } from './routes/student-life'
import { Route as AlumniDirectoryRouteImport } from './routes/alumni/directory'
import { Route as CampusStoresIndexRouteImport } from './routes/campus-stores.index'
import { Route as CampusStoresSlugRouteImport } from './routes/campus-stores.$slug'
import { Route as ClubsSlugRouteImport } from './routes/clubs.$slug'
import { Route as AlumniDirectoryIdRouteImport } from './routes/alumni/directory/$id'
import { Route as AlumniDirectoryAdminRouteImport } from './routes/alumni/directory.admin'
import { Route as AlumniDirectoryBusinessesRouteImport } from './routes/alumni/directory.businesses'
import { Route as AlumniDirectoryClaimRouteImport } from './routes/alumni/directory.claim'
import { Route as AlumniDirectoryLoginRouteImport } from './routes/alumni/directory.login'
import { Route as AlumniDirectoryRegisterRouteImport } from './routes/alumni/directory.register'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsRoute = AcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumniRoute = AlumniRouteImport.update({
  id: '/alumni',
  path: '/alumni',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleticsRoute = AthleticsRouteImport.update({
  id: '/athletics',
  path: '/athletics',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsRoute = ClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GivingRoute = GivingRouteImport.update({
  id: '/giving',
  path: '/giving',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLifeRoute = StudentLifeRouteImport.update({
  id: '/student-life',
  path: '/student-life',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumniDirectoryRoute = AlumniDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => AlumniRoute,
} as any)
const CampusStoresIndexRoute = CampusStoresIndexRouteImport.update({
  id: '/campus-stores/',
  path: '/campus-stores/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusStoresSlugRoute = CampusStoresSlugRouteImport.update({
  id: '/campus-stores/$slug',
  path: '/campus-stores/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsSlugRoute = ClubsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ClubsRoute,
} as any)
const AlumniDirectoryIdRoute = AlumniDirectoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AlumniDirectoryRoute,
} as any)
const AlumniDirectoryAdminRoute = AlumniDirectoryAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AlumniDirectoryRoute,
} as any)
const AlumniDirectoryBusinessesRoute =
  AlumniDirectoryBusinessesRouteImport.update({
    id: '/businesses',
    path: '/businesses',
    getParentRoute: () => AlumniDirectoryRoute,
  } as any)
const AlumniDirectoryClaimRoute = AlumniDirectoryClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => AlumniDirectoryRoute,
} as any)
const AlumniDirectoryLoginRoute = AlumniDirectoryLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AlumniDirectoryRoute,
} as any)
const AlumniDirectoryRegisterRoute = AlumniDirectoryRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AlumniDirectoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/alumni': typeof AlumniRouteWithChildren
  '/athletics': typeof AthleticsRoute
  '/calendar': typeof CalendarRoute
  '/clubs': typeof ClubsRouteWithChildren
  '/contact': typeof ContactRoute
  '/giving': typeof GivingRoute
  '/student-life': typeof StudentLifeRoute
  '/alumni/directory': typeof AlumniDirectoryRouteWithChildren
  '/campus-stores/$slug': typeof CampusStoresSlugRoute
  '/clubs/$slug': typeof ClubsSlugRoute
  '/campus-stores/': typeof CampusStoresIndexRoute
  '/alumni/directory/$id': typeof AlumniDirectoryIdRoute
  '/alumni/directory/admin': typeof AlumniDirectoryAdminRoute
  '/alumni/directory/businesses': typeof AlumniDirectoryBusinessesRoute
  '/alumni/directory/claim': typeof AlumniDirectoryClaimRoute
  '/alumni/directory/login': typeof AlumniDirectoryLoginRoute
  '/alumni/directory/register': typeof AlumniDirectoryRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/alumni': typeof AlumniRouteWithChildren
  '/athletics': typeof AthleticsRoute
  '/calendar': typeof CalendarRoute
  '/clubs': typeof ClubsRouteWithChildren
  '/contact': typeof ContactRoute
  '/giving': typeof GivingRoute
  '/student-life': typeof StudentLifeRoute
  '/alumni/directory': typeof AlumniDirectoryRouteWithChildren
  '/campus-stores/$slug': typeof CampusStoresSlugRoute
  '/clubs/$slug': typeof ClubsSlugRoute
  '/campus-stores': typeof CampusStoresIndexRoute
  '/alumni/directory/$id': typeof AlumniDirectoryIdRoute
  '/alumni/directory/admin': typeof AlumniDirectoryAdminRoute
  '/alumni/directory/businesses': typeof AlumniDirectoryBusinessesRoute
  '/alumni/directory/claim': typeof AlumniDirectoryClaimRoute
  '/alumni/directory/login': typeof AlumniDirectoryLoginRoute
  '/alumni/directory/register': typeof AlumniDirectoryRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/alumni': typeof AlumniRouteWithChildren
  '/athletics': typeof AthleticsRoute
  '/calendar': typeof CalendarRoute
  '/clubs': typeof ClubsRouteWithChildren
  '/contact': typeof ContactRoute
  '/giving': typeof GivingRoute
  '/student-life': typeof StudentLifeRoute
  '/alumni/directory': typeof AlumniDirectoryRouteWithChildren
  '/campus-stores/$slug': typeof CampusStoresSlugRoute
  '/clubs/$slug': typeof ClubsSlugRoute
  '/campus-stores/': typeof CampusStoresIndexRoute
  '/alumni/directory/$id': typeof AlumniDirectoryIdRoute
  '/alumni/directory/admin': typeof AlumniDirectoryAdminRoute
  '/alumni/directory/businesses': typeof AlumniDirectoryBusinessesRoute
  '/alumni/directory/claim': typeof AlumniDirectoryClaimRoute
  '/alumni/directory/login': typeof AlumniDirectoryLoginRoute
  '/alumni/directory/register': typeof AlumniDirectoryRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academics'
    | '/admissions'
    | '/alumni'
    | '/athletics'
    | '/calendar'
    | '/clubs'
    | '/contact'
    | '/giving'
    | '/student-life'
    | '/alumni/directory'
    | '/campus-stores/$slug'
    | '/clubs/$slug'
    | '/campus-stores/'
    | '/alumni/directory/$id'
    | '/alumni/directory/admin'
    | '/alumni/directory/businesses'
    | '/alumni/directory/claim'
    | '/alumni/directory/login'
    | '/alumni/directory/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academics'
    | '/admissions'
    | '/alumni'
    | '/athletics'
    | '/calendar'
    | '/clubs'
    | '/contact'
    | '/giving'
    | '/student-life'
    | '/alumni/directory'
    | '/campus-stores/$slug'
    | '/clubs/$slug'
    | '/campus-stores'
    | '/alumni/directory/$id'
    | '/alumni/directory/admin'
    | '/alumni/directory/businesses'
    | '/alumni/directory/claim'
    | '/alumni/directory/login'
    | '/alumni/directory/register'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academics'
    | '/admissions'
    | '/alumni'
    | '/athletics'
    | '/calendar'
    | '/clubs'
    | '/contact'
    | '/giving'
    | '/student-life'
    | '/alumni/directory'
    | '/campus-stores/$slug'
    | '/clubs/$slug'
    | '/campus-stores/'
    | '/alumni/directory/$id'
    | '/alumni/directory/admin'
    | '/alumni/directory/businesses'
    | '/alumni/directory/claim'
    | '/alumni/directory/login'
    | '/alumni/directory/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademicsRoute: typeof AcademicsRoute
  AdmissionsRoute: typeof AdmissionsRoute
  AlumniRoute: typeof AlumniRouteWithChildren
  AthleticsRoute: typeof AthleticsRoute
  CalendarRoute: typeof CalendarRoute
  ClubsRoute: typeof ClubsRouteWithChildren
  ContactRoute: typeof ContactRoute
  GivingRoute: typeof GivingRoute
  StudentLifeRoute: typeof StudentLifeRoute
  CampusStoresSlugRoute: typeof CampusStoresSlugRoute
  CampusStoresIndexRoute: typeof CampusStoresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics': {
      id: '/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AcademicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumni': {
      id: '/alumni'
      path: '/alumni'
      fullPath: '/alumni'
      preLoaderRoute: typeof AlumniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athletics': {
      id: '/athletics'
      path: '/athletics'
      fullPath: '/athletics'
      preLoaderRoute: typeof AthleticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs': {
      id: '/clubs'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof ClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giving': {
      id: '/giving'
      path: '/giving'
      fullPath: '/giving'
      preLoaderRoute: typeof GivingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-life': {
      id: '/student-life'
      path: '/student-life'
      fullPath: '/student-life'
      preLoaderRoute: typeof StudentLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumni/directory': {
      id: '/alumni/directory'
      path: '/directory'
      fullPath: '/alumni/directory'
      preLoaderRoute: typeof AlumniDirectoryRouteImport
      parentRoute: typeof AlumniRoute
    }
    '/campus-stores/': {
      id: '/campus-stores/'
      path: '/campus-stores'
      fullPath: '/campus-stores/'
      preLoaderRoute: typeof CampusStoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus-stores/$slug': {
      id: '/campus-stores/$slug'
      path: '/campus-stores/$slug'
      fullPath: '/campus-stores/$slug'
      preLoaderRoute: typeof CampusStoresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/$slug': {
      id: '/clubs/$slug'
      path: '/$slug'
      fullPath: '/clubs/$slug'
      preLoaderRoute: typeof ClubsSlugRouteImport
      parentRoute: typeof ClubsRoute
    }
    '/alumni/directory/$id': {
      id: '/alumni/directory/$id'
      path: '/$id'
      fullPath: '/alumni/directory/$id'
      preLoaderRoute: typeof AlumniDirectoryIdRouteImport
      parentRoute: typeof AlumniDirectoryRoute
    }
    '/alumni/directory/admin': {
      id: '/alumni/directory/admin'
      path: '/admin'
      fullPath: '/alumni/directory/admin'
      preLoaderRoute: typeof AlumniDirectoryAdminRouteImport
      parentRoute: typeof AlumniDirectoryRoute
    }
    '/alumni/directory/businesses': {
      id: '/alumni/directory/businesses'
      path: '/businesses'
      fullPath: '/alumni/directory/businesses'
      preLoaderRoute: typeof AlumniDirectoryBusinessesRouteImport
      parentRoute: typeof AlumniDirectoryRoute
    }
    '/alumni/directory/claim': {
      id: '/alumni/directory/claim'
      path: '/claim'
      fullPath: '/alumni/directory/claim'
      preLoaderRoute: typeof AlumniDirectoryClaimRouteImport
      parentRoute: typeof AlumniDirectoryRoute
    }
    '/alumni/directory/login': {
      id: '/alumni/directory/login'
      path: '/login'
      fullPath: '/alumni/directory/login'
      preLoaderRoute: typeof AlumniDirectoryLoginRouteImport
      parentRoute: typeof AlumniDirectoryRoute
    }
    '/alumni/directory/register': {
      id: '/alumni/directory/register'
      path: '/register'
      fullPath: '/alumni/directory/register'
      preLoaderRoute: typeof AlumniDirectoryRegisterRouteImport
      parentRoute: typeof AlumniDirectoryRoute
    }
  }
}

interface AlumniDirectoryRouteChildren {
  AlumniDirectoryIdRoute: typeof AlumniDirectoryIdRoute
  AlumniDirectoryAdminRoute: typeof AlumniDirectoryAdminRoute
  AlumniDirectoryBusinessesRoute: typeof AlumniDirectoryBusinessesRoute
  AlumniDirectoryClaimRoute: typeof AlumniDirectoryClaimRoute
  AlumniDirectoryLoginRoute: typeof AlumniDirectoryLoginRoute
  AlumniDirectoryRegisterRoute: typeof AlumniDirectoryRegisterRoute
}

const AlumniDirectoryRouteChildren: AlumniDirectoryRouteChildren = {
  AlumniDirectoryIdRoute: AlumniDirectoryIdRoute,
  AlumniDirectoryAdminRoute: AlumniDirectoryAdminRoute,
  AlumniDirectoryBusinessesRoute: AlumniDirectoryBusinessesRoute,
  AlumniDirectoryClaimRoute: AlumniDirectoryClaimRoute,
  AlumniDirectoryLoginRoute: AlumniDirectoryLoginRoute,
  AlumniDirectoryRegisterRoute: AlumniDirectoryRegisterRoute,
}

const AlumniDirectoryRouteWithChildren = AlumniDirectoryRoute._addFileChildren(
  AlumniDirectoryRouteChildren,
)

interface AlumniRouteChildren {
  AlumniDirectoryRoute: typeof AlumniDirectoryRouteWithChildren
}

const AlumniRouteChildren: AlumniRouteChildren = {
  AlumniDirectoryRoute: AlumniDirectoryRouteWithChildren,
}

const AlumniRouteWithChildren =
  AlumniRoute._addFileChildren(AlumniRouteChildren)

interface ClubsRouteChildren {
  ClubsSlugRoute: typeof ClubsSlugRoute
}

const ClubsRouteChildren: ClubsRouteChildren = {
  ClubsSlugRoute: ClubsSlugRoute,
}

const ClubsRouteWithChildren = ClubsRoute._addFileChildren(ClubsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademicsRoute: AcademicsRoute,
  AdmissionsRoute: AdmissionsRoute,
  AlumniRoute: AlumniRouteWithChildren,
  AthleticsRoute: AthleticsRoute,
  CalendarRoute: CalendarRoute,
  ClubsRoute: ClubsRouteWithChildren,
  ContactRoute: ContactRoute,
  GivingRoute: GivingRoute,
  StudentLifeRoute: StudentLifeRoute,
  CampusStoresSlugRoute: CampusStoresSlugRoute,
  CampusStoresIndexRoute: CampusStoresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
